version: '3.4'

services:
  customer.microservice:
    image: ${DOCKER_REGISTRY-}customermicroservice
    build:
      context: .
      dockerfile: Customer.Microservice/Dockerfile

  gateway.webapi:
    image: ${DOCKER_REGISTRY-}gatewaywebapi
    build:
      context: .
      dockerfile: Gateway.WebApi/Dockerfile

