version: '3.4'

services:
  customer.microservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:44000
    ports:
      - "44000:44000"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  gateway.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:42000
    ports:
      - "42000:42000"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
